name: .NET Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore BasicMathAppProper.sln

    - name: Build
      run: dotnet build BasicMathAppProper.sln --no-restore --configuration Release

    - name: Test 2_a
      run: dotnet test BasicMathAppProper.sln --configuration Release --no-build --verbosity normal
